### PR TITLE
Open the app on clicking notification

### PR DESCRIPTION
**Pull request by shashikantdurge**

### CODE REVIEW

**Comment by shashikantdurge** [comment]
Fixes #420

**Review by jhomlala — CHANGES_REQUESTED** [review]
I don't think so all apps have MainActivity. You need to setup another way to open app. Maybe add some parameter like name of activity which can be configured from dart?

**Comment by shashikantdurge** [comment]
Yeah good point, it can be configured from notification configuration.

**Comment by jhomlala** [comment]
@shashikantdurge Are you going to fix it in near future? I mean there's no stress on that, but I just need to know that you'll continue working on it.

**Comment by shashikantdurge** [comment]
Yes, I will be. Got a little busy.

**Comment by jhomlala** [comment]
@shashikantdurge I've already added activityName parameter in notification configuration. Thank you for your PR.

**Pull request merged**
