### PR TITLE
Add dependencies on GCDWebServer and PINCache

### PR DESCRIPTION
**Pull request by twogood**
Trying to fix part of https://github.com/jhomlala/betterplayer/issues/714

To be more exact, try to fix this error message, which sometimes also lists GCDWebServer:

```
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_PINCache", referenced from:
          objc-class-ref in CacheManager.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### CODE REVIEW

**Comment by jhomlala** [comment]
@twogood Before merging this PR I need to know when does this problem occur. Can you prepare some reproducible example?

**Comment by twogood** [comment]
You know the old saying:

| The definition of insanity is doing the same thing over and over again and expecting a different result.

The client project that me and my team have inherited and are currently working on failed on compile most of the time before adding these as explicit dependencies. We have spent many hours trying to figure out why. With this patch it works every time. 

Linkers are a species of their own. There is even a "classic" book called "Linkers and loaders" for those who want to know more how linkers work. 

But I digress. I don't have an isolated example but as the better player code explicitly references these pods they should also be explicit references from the better player pod. It is unwise to depend on transitive dependencies.

**Comment by twogood** [comment]
This article shows a cocoa pods example for specifying the same dependency on different levels in the dependency tree with proper version resolving:

 https://link.medium.com/9xXAjB5cZkb

**Comment by twogood** [comment]
Here is an example that (sometimes) fails the same way:

https://github.com/twogood/better_player_pr787

**Comment by twogood** [comment]
image

**Comment by twogood** [comment]
And sometimes... "Build succeeded"

**Comment by ndahlquist** [comment]
For what it's worth, I also experienced this error yesterday (and then it resolved itself after a clean build). Seems like a good idea to explicitly add the transitive dependencies if it can make the build more reliable!

**Comment by twogood** [comment]
Actually they are also direct dependencies in the source code:

image

**Comment by aignerjo** [comment]
+1

@twogood's solution works.

**Comment by ndahlquist** [comment]
I added this patch too! No more linker errors :)

**Comment by garlicPasta** [comment]
It also fixed the error for me when building for a real device 👍 
Simulator was not having this error.

**Comment by windows7lake** [comment]
It’s help

**Comment by jhomlala** [comment]
LGTM, thanks.

**Pull request merged**
