### PR TITLE
Fix loading large video from network

### PR DESCRIPTION
**Pull request by anhnt**
Document from Apple: https://developer.apple.com/documentation/avfoundation/avplayer/1643482-automaticallywaitstominimizestal

`automaticallyWaitsToMinimizeStalling` is true by default. So just need removing the redundant code

### CODE REVIEW

**Comment by jhomlala** [comment]
@anhnt Does your fix help with this issue: https://github.com/jhomlala/betterplayer/issues/224?

**Comment by anhnt** [comment]
@jhomlala it works well on XS Max on iOS 14.5

image

**Comment by jhomlala** [comment]
There's issue with iOS 12.x not with 14.x. Please check again with 12.x and let me know.

**Comment by jhomlala** [comment]
Any update? Also just to mention, Better Player has special mechanism to handle stalled state, so this flag is required to be false.

**Comment by jhomlala** [comment]
@anhnt I'm sorry I need to close it. You didn't provide details and for me this fix won't solve this issue at all. Anyway thanks for helping.

**Pull request closed without merging**
