### PR TITLE
Fixed issue of flutter 3.22.0

### PR DESCRIPTION
**Pull request by Syed-Waleed-Shah**

### CODE REVIEW

**Comment by rjkolli7** [comment]
Hey Jhomlala, could you please approve this pull request. In latest flutter encountering this issue and unable to build apps

**Review by kp4karma — APPROVED** [review]

**Comment by jhomlala** [comment]
Please check latest release, it's already fixed.

**Comment by waleed-brandverse** [comment]
> Please check latest release, it's already fixed.

Yes. I am closing this PR now.

**Comment by Syed-Waleed-Shah** [comment]
> Please check latest release, it's already fixed.

Yes. I am closing this PR.

**Pull request closed without merging**
