### PR TITLE
Fix iOS caching + add iOS feature: preCaching

### PR DESCRIPTION
**Pull request by themadmrj**
On iOS, caching currently does not work as expected, because the cacheKey is ignored. This PR builds a new caching system on iOS which fixes this and also allows pre-caching, which I had previously only added on Android. With this PR, betterplayer will be the only library that fully supports caching and pre-caching videos on both platforms.
Limitations: preCaching on iOS currently does not support pre-caching only a chunk of the file. The whole file will be downloaded, therefore devs should be careful when using the feature with big files.
HLS: the current system is to load everything into memory and save the file to disk once downloaded, so if you plan to read a stream for 2 hours, probably not. But anyway, who uses cache with hls? Since I don't, I recon someone tests it with HLS, I can't tell what the result will be. It should at least play since the base it still an AVPlayerItem.

This is the response to the #548 lost in translation...

### CODE REVIEW

**Comment by themadmrj** [comment]
@jhomlala please keep me posted when you've checked the last commit :)

**Comment by berlinLovesArt** [comment]
Hey @themadmrj I tried this PR but had the following error: 

```
Xcode's output:
↳
    3 warnings generated.
    /Users/berlin/Presence/ios/Pods/Swime/Sources/Swime.swift:41:21: warning: 'init(bytes:)' is deprecated: use `init(_:)` instead
        self.init(data: Data(bytes: bytes))
                        ^
    /Users/berlin/Presence/ios/Pods/Swime/Sources/Swime.swift:41:21: warning: 'init(bytes:)' is deprecated: use `init(_:)` instead
        self.init(data: Data(bytes: bytes))
                        ^
    /Users/berlin/Presence/ios/Pods/Swime/Sources/Swime.swift:41:21: warning: 'init(bytes:)' is deprecated: use `init(_:)` instead
        self.init(data: Data(bytes: bytes))
                        ^
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/better_player-umbrella.h"
            ^
    /Users/berlin/Presence/ios/Pods/Target Support Files/better_player/better_player-umbrella.h:13:9: note: in file included from /Users/berlin/Presence/ios/Pods/Target Support
    Files/better_player/better_player-umbrella.h:13:
    #import "BetterPlayer.h"
            ^
    /Users/berlin/flutter/.pub-cache/git/betterplayer-06c301a4a5e6035c17f25d9f3551351da7a9582c/ios/Classes/BetterPlayer.h:54:34: warning: 'width' used as the name of the previous
    parameter rather than as part of the selector
    - (void)setTrackParameters:(int) width: (int) height: (int)bitrate;
                                     ^
    /Users/berlin/flutter/.pub-cache/git/betterplayer-06c301a4a5e6035c17f25d9f3551351da7a9582c/ios/Classes/BetterPlayer.h:54:34: note: introduce a parameter name to make 'width' part of
    the selector
    - (void)setTrackParameters:(int) width: (int) height: (int)bitrate;
                                     ^
    /Users/berlin/flutter/.pub-cache/git/betterplayer-06c301a4a5e6035c17f25d9f3551351da7a9582c/ios/Classes/BetterPlayer.h:54:39: note: or insert whitespace before ':' to use 'width' as
    parameter name and have an empty entry in the selector
    - (void)setTrackParameters:(int) width: (int) height: (int)bitrate;
                                          ^
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/better_player-umbrella.h"
            ^
    /Users/berlin/Presence/ios/Pods/Target Support Files/better_player/better_player-umbrella.h:13:9: note: in file included from /Users/berlin/Presence/ios/Pods/Target Support
    Files/better_player/better_player-umbrella.h:13:
    #import "BetterPlayer.h"
            ^
    /Users/berlin/flutter/.pub-cache/git/betterplayer-06c301a4a5e6035c17f25d9f3551351da7a9582c/ios/Classes/BetterPlayer.h:54:47: warning: 'height' used as the name of the previous
    parameter rather than as part of the selector
    - (void)setTrackParameters:(int) width: (int) height: (int)bitrate;
                                                  ^
    /Users/berlin/flutter/.pub-cache/git/betterplayer-06c301a4a5e6035c17f25d9f3551351da7a9582c/ios/Classes/BetterPlayer.h:54:47: note: introduce a parameter name to make 'height' part of
    the selector
    - (void)setTrackParameters:(int) width: (int) height: (int)bitrate;
                                                  ^
    /Users/berlin/flutter/.pub-cache/git/betterplayer-06c301a4a5e6035c17f25d9f3551351da7a9582c/ios/Classes/BetterPlayer.h:54:53: note: or insert whitespace before ':' to use 'height' as
    parameter name and have an empty entry in the selector
    - (void)setTrackParameters:(int) width: (int) height: (int)bitrate;
                                                        ^
    /Users/berlin/flutter/.pub-cache/git/betterplayer-06c301a4a5e6035c17f25d9f3551351da7a9582c/ios/Classes/CacheManager.swift:23:40: error: generic parameter 'Key' could not be inferred
        lazy var storage: Cache.Storage? = {
                                           ^
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/better_player-umbrella.h"
            ^
    /Users/berlin/Presence/ios/Pods/Target Support Files/better_player/better_player-umbrella.h:13:9: note: in file included from /Users/berlin/Presence/ios/Pods/Target Support
    Files/better_player/better_player-umbrella.h:13:
    #import "BetterPlayer.h"
            ^
    /Users/berlin/flutter/.pub-cache/git/betterplayer-06c301a4a5e6035c17f25d9f3551351da7a9582c/ios/Classes/CachingPlayerItem.swift:79:46: warning: cast from 'Dictionary<NSObject,
    AnyObject>.Element' (aka '(key: NSObject, value: AnyObject)') to unrelated type 'String' always fails
                        request.setValue((_value as! String), forHTTPHeaderField: (_key as! String))
                                          ~~~~~~ ^   ~~~~~~
    /Users/berlin/flutter/.pub-cache/git/betterplayer-06c301a4a5e6035c17f25d9f3551351da7a9582c/ios/Classes/CachingPlayerItem.swift:79:85: warning: cast from 'Int' to unrelated type
    'String' always fails
                        request.setValue((_value as! String), forHTTPHeaderField: (_key as! String))
                                                                                   ~~~~ ^   ~~~~~~
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner
    editor. (in target 'Runner' from project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro.
```

Here's my flutter doctor -v output:

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale en-IN)
    • Flutter version 2.2.3 at /Users/berlin/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/berlin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • CB8A1B9B-05FD-4AC8-B603-FBEA9A46E589 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

Any pointers would be appreciated.

**Comment by themadmrj** [comment]
Compile issues are fixed now, Ioseph

**Comment by berlinLovesArt** [comment]
@themadmrj I am not Ioseph :) He suggested me this plugin. Thanks for the fix.

**Comment by jhomlala** [comment]
@themadmrj I have changed base branch to apply my small fixes. This feature should be in the next release. Again thanks for PR.

**Comment by themadmrj** [comment]
@jhomlala sounds good!

**Pull request merged**
