### PR TITLE
Fixed dispose bug, and exported controls files

### PR DESCRIPTION
**Pull request by mkranus**

### CODE REVIEW

**Comment by jhomlala** [comment]
Can you specify what's the purpose of this PR?

**Comment by mkranus** [comment]
- a bug in the force close condition of the dispose function
- exported controls widget files which were not exported (but can be useful)
- added asserts which could be useful when modifying values

**Comment by jhomlala** [comment]
@mkranus Please resolve issues from conversation.

**Comment by jhomlala** [comment]
@mkranus This is last call. Please resolve comments or I'll close this PR.

**Pull request closed without merging**
